export const store = {
  sets: [
    { code: 'base1',
      name: 'Base',
      totalCards: 102 },
    { code: 'base2',
      name: 'Jungle',
      totalCards: 64 },
    { code: 'basep',
      name: 'Wizards Black Star Promos',
      totalCards: 53 },
    { code: 'base3',
      name: 'Fossil',
      totalCards: 62 },
    { code: 'base4',
      name: 'Base Set 2',
      totalCards: 130 },
    { code: 'base5',
      name: 'Team Rocket',
      totalCards: 83 },
    { code: 'gym1',
      name: 'Gym Heros',
      totalCards: 132 },
    { code: 'gym2',
      name: 'Gym Challenge',
      totalCards: 132 },
    { code: 'neo1',
      name: 'Neo Genesis',
      totalCards: 111 },
    { code: 'neo2',
      name: 'Neo Discovery',
      totalCards: 75 },
    { code: 'si1',
      name: 'Southern Islands',
      totalCards: 18 },
    { code: 'neo3',
      name: 'Neo Revolution',
      totalCards: 66 },
    { code: 'neo4',
      name: 'Neo Destiny',
      totalCards: 113 },
    { code: 'base6',
      name: 'Legendary Collection',
      totalCards: 110 },
    { code: 'ecard1',
      name: 'Expedition Base Set',
      totalCards: 165 },
    // calling ecard2 set returns totalCards = 186
    { code: 'ecard2',
      name: 'Aquapolis',
      totalCards: 182 },
    { code: 'ecard3',
      name: 'Skyridge',
      totalCards: 182 }
  ],
  types: [
    { type: 'Grass',
      imageUrl: 'https://i.imgur.com/t4xvNDl.png' },
    { type: 'Fire',
      imageUrl: 'https://i.imgur.com/bsmavYI.png' },
    { type: 'Water',
      imageUrl: 'https://i.imgur.com/8BFSwEa.png' },
    { type: 'Lightning',
      imageUrl: 'https://i.imgur.com/OPO7XE4.png' },
    { type: 'Fighting',
      imageUrl: 'https://i.imgur.com/kOOT3oz.png' },
    { type: 'Psychic',
      imageUrl: 'https://i.imgur.com/wwb2X65.png' },
    { type: 'Colorless',
      imageUrl: 'https://i.imgur.com/Y2prJ63.png' },
    { type: 'Darkness',
      imageUrl: 'https://i.imgur.com/a5gl2JU.png' },
    { type: 'Metal',
      imageUrl: 'https://i.imgur.com/wOWplV9.png' },
    { type: 'None',
      imageUrl: 'https://i.imgur.com/zMgwst5.png' }
  ]
}
